title: Shpat Cheliku # your name (or website title) here
logo: "/images/shpat.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hello, I'm Shpat Cheliku, a Computing Science MSc student at Utrecht University. Currently I'm also Data Science intern at the Ministry of Infrastructure and Water Management of the Netherlands. 
  <br><br>
  My areas of expertise are Data Science, Machine Learning and Data Visualization.
  I mostly use Python, R and C# for my projects.
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/shpatcheliku/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
